Repository AbsaOSS/cps-shared-ui, pull requests merged in 2024-03, with the labels that each got.

#347 #320 Define types and interfaces in docs
  api-generator/api-generator.js
  projects/composition/src/app/api-data/cps-autocomplete.json
  projects/composition/src/app/api-data/cps-button-toggle.json
  projects/composition/src/app/api-data/cps-datepicker.json
  projects/composition/src/app/api-data/cps-dialog.json
  projects/composition/src/app/api-data/cps-icon.json
  projects/composition/src/app/api-data/cps-input.json
  projects/composition/src/app/api-data/cps-menu.json
  projects/composition/src/app/api-data/cps-notification.json
  projects/composition/src/app/api-data/cps-radio-group.json
  projects/composition/src/app/api-data/cps-select.json
  projects/composition/src/app/api-data/cps-sidebar-menu.json
  projects/composition/src/app/api-data/cps-tab-group.json
  projects/composition/src/app/api-data/cps-table.json
  projects/composition/src/app/api-data/cps-timepicker.json
  projects/composition/src/app/api-data/cps-tooltip.json
  projects/composition/src/app/api-data/cps-tree-autocomplete.json
  projects/composition/src/app/api-data/cps-tree-select.json
  projects/composition/src/app/api-data/cps-tree-table.json
  projects/composition/src/app/api-data/types_map.json
  projects/composition/src/app/app-routing.module.ts
  projects/composition/src/app/components/component-docs-viewer/component-docs-viewer.component.html
  projects/composition/src/app/components/component-docs-viewer/component-docs-viewer.component.scss
  projects/composition/src/app/components/component-docs-viewer/component-docs-viewer.component.ts
  projects/composition/src/app/components/navigation-sidebar/navigation-sidebar.component.ts
  projects/composition/src/app/components/service-docs-viewer/service-docs-viewer.component.html
  projects/composition/src/app/components/service-docs-viewer/service-docs-viewer.component.scss
  projects/composition/src/app/components/service-docs-viewer/service-docs-viewer.component.ts
  projects/composition/src/app/components/viewer/viewer.component.ts
  projects/composition/src/app/models/component-api.model.ts
  projects/composition/src/app/models/service-api.model.ts
  projects/composition/src/app/pages/colors-page/colors-page/colors-page.component.ts
  projects/composition/src/app/pages/icons-page/icons-page/icons-page.component.ts
  projects/composition/src/app/pipes/detect-type.pipe.ts
  projects/composition/src/app/pipes/object-entries.pipe.ts
  projects/composition/src/styles.scss
  projects/cps-ui-kit/src/lib/components/cps-autocomplete/cps-autocomplete.component.ts
  projects/cps-ui-kit/src/lib/components/cps-button-toggle/cps-button-toggle.component.ts
  projects/cps-ui-kit/src/lib/components/cps-datepicker/cps-datepicker.component.ts
  projects/cps-ui-kit/src/lib/components/cps-icon/cps-icon.component.ts
  projects/cps-ui-kit/src/lib/components/cps-input/cps-input.component.ts
  projects/cps-ui-kit/src/lib/components/cps-menu/cps-menu.component.ts
  projects/cps-ui-kit/src/lib/components/cps-radio-group/cps-radio-group.component.ts
  projects/cps-ui-kit/src/lib/components/cps-select/cps-select.component.ts
  projects/cps-ui-kit/src/lib/components/cps-sidebar-menu/cps-sidebar-menu.component.ts
  projects/cps-ui-kit/src/lib/components/cps-tab-group/cps-tab-group.component.ts
  projects/cps-ui-kit/src/lib/components/cps-table/cps-column-filter-types.ts
  projects/cps-ui-kit/src/lib/components/cps-table/cps-table.component.ts
  projects/cps-ui-kit/src/lib/components/cps-timepicker/cps-timepicker.component.ts
  projects/cps-ui-kit/src/lib/components/cps-tree-autocomplete/cps-tree-autocomplete.component.ts
  projects/cps-ui-kit/src/lib/components/cps-tree-select/cps-tree-select.component.ts
  projects/cps-ui-kit/src/lib/components/cps-tree-table/cps-tree-table.component.ts
  projects/cps-ui-kit/src/lib/directives/cps-tooltip/cps-tooltip.directive.ts
  projects/cps-ui-kit/src/lib/services/cps-notification/utils/cps-notification-config.ts
  projects/cps-ui-kit/src/lib/services/cps-notification/utils/internal/cps-notification-data.ts
Labels: enhancement, composition

#354 #331 CpsDialogService use applicationref instead of viewcontainerref and provide in root
  api-generator/api-generator.js
  projects/composition/src/app/api-data/cps-dialog.json
  projects/composition/src/app/app.module.ts
  projects/composition/src/app/components/service-docs-viewer/service-docs-viewer.component.ts
  projects/composition/src/app/pages/dialog-page/dialog-page.component.html
  projects/composition/src/app/pages/dialog-page/dialog-page.component.scss
  projects/composition/src/app/pages/dialog-page/dialog-page.component.ts
  projects/composition/src/styles.scss
  projects/cps-ui-kit/src/lib/services/cps-dialog/cps-dialog.service.ts
  projects/cps-ui-kit/src/lib/services/cps-dialog/internal/components/cps-confirmation/cps-confirmation.component.ts
Labels: enhancement, library

#357 Provided showChevron prop to autocompletes and selects
  projects/composition/src/app/api-data/cps-select.json
  projects/composition/src/app/api-data/cps-tree-autocomplete.json
  projects/composition/src/app/api-data/cps-tree-select.json
  projects/composition/src/app/api-data/internal.json
  projects/composition/src/app/pages/autocomplete-page/autocomplete-page.component.html
  projects/composition/src/app/pages/select-page/select-page.component.html
  projects/composition/src/app/pages/tree-autocomplete-page/tree-autocomplete-page.component.html
  projects/composition/src/app/pages/tree-select-page/tree-select-page.component.html
  projects/cps-ui-kit/src/lib/components/cps-select/cps-select.component.html
  projects/cps-ui-kit/src/lib/components/cps-select/cps-select.component.ts
  projects/cps-ui-kit/src/lib/components/cps-tree-autocomplete/cps-tree-autocomplete.component.html
  projects/cps-ui-kit/src/lib/components/cps-tree-select/cps-tree-select.component.html
  projects/cps-ui-kit/src/lib/components/internal/cps-base-tree-dropdown/cps-base-tree-dropdown.component.ts
Labels: enhancement, library

#358 Made "event" arg optional in clear method in tree-based selects
  projects/cps-ui-kit/src/lib/components/cps-tree-autocomplete/cps-tree-autocomplete.component.ts
  projects/cps-ui-kit/src/lib/components/internal/cps-base-tree-dropdown/cps-base-tree-dropdown.component.ts
Labels: enhancement, library

#359 Fix tree-based selects initial expanded state
  projects/composition/src/app/api-data/cps-tree-autocomplete.json
  projects/composition/src/app/api-data/cps-tree-select.json
  projects/composition/src/app/api-data/internal.json
  projects/composition/src/app/pages/tree-autocomplete-page/tree-autocomplete-page.component.html
  projects/composition/src/app/pages/tree-select-page/tree-select-page.component.html
  projects/cps-ui-kit/src/lib/components/cps-tree-autocomplete/cps-tree-autocomplete.component.html
  projects/cps-ui-kit/src/lib/components/cps-tree-autocomplete/cps-tree-autocomplete.component.scss
  projects/cps-ui-kit/src/lib/components/cps-tree-select/cps-tree-select.component.html
  projects/cps-ui-kit/src/lib/components/cps-tree-select/cps-tree-select.component.scss
  projects/cps-ui-kit/src/lib/components/internal/cps-base-tree-dropdown/cps-base-tree-dropdown.component.ts
Labels: bug, library

#360 Retrieve default values for the input properties defined using setters/getters
  api-generator/api-generator.js
  projects/composition/src/app/api-data/cps-checkbox.json
  projects/composition/src/app/api-data/cps-datepicker.json
  projects/composition/src/app/api-data/cps-input.json
  projects/composition/src/app/api-data/cps-switch.json
  projects/composition/src/app/api-data/cps-tab-group.json
  projects/composition/src/app/api-data/cps-table.json
  projects/composition/src/app/api-data/cps-tag.json
  projects/composition/src/app/api-data/cps-textarea.json
  projects/composition/src/app/api-data/cps-tree-table.json
  projects/cps-ui-kit/src/lib/components/cps-checkbox/cps-checkbox.component.ts
  projects/cps-ui-kit/src/lib/components/cps-datepicker/cps-datepicker.component.ts
  projects/cps-ui-kit/src/lib/components/cps-input/cps-input.component.ts
  projects/cps-ui-kit/src/lib/components/cps-switch/cps-switch.component.ts
  projects/cps-ui-kit/src/lib/components/cps-tab-group/cps-tab-group.component.ts
  projects/cps-ui-kit/src/lib/components/cps-table/cps-table.component.ts
  projects/cps-ui-kit/src/lib/components/cps-tag/cps-tag.component.ts
  projects/cps-ui-kit/src/lib/components/cps-textarea/cps-textarea.component.ts
  projects/cps-ui-kit/src/lib/components/cps-tree-table/cps-tree-table.component.ts
Labels: composition

#363 Show description of service method parameters and make their types clickable
  projects/composition/src/app/app-routing.module.ts
  projects/composition/src/app/components/navigation-sidebar/navigation-sidebar.component.ts
  projects/composition/src/app/components/service-docs-viewer/service-docs-viewer.component.html
  projects/composition/src/app/components/service-docs-viewer/service-docs-viewer.component.scss
  projects/composition/src/app/components/service-docs-viewer/service-docs-viewer.component.ts
Labels: enhancement, composition
