Repository AbsaOSS/cps-shared-ui, pull requests merged in 2024-02, with the labels that each got.

#327 Fix tabs and expansion panel
  projects/composition/src/app/pages/expansion-panel-page/expansion-panel-page.component.html
  projects/composition/src/app/pages/tab-group-page/tab-group-page.component.scss
  projects/composition/src/app/pages/tab-group-page/tab-group-page.component.ts
  projects/composition/src/app/pages/table-page/table-page.component.scss
  projects/composition/src/app/pages/table-page/table-page.component.ts
  projects/composition/src/app/pages/tree-table-page/tree-table-page.component.scss
  projects/composition/src/app/pages/tree-table-page/tree-table-page.component.ts
  projects/cps-ui-kit/src/lib/components/cps-expansion-panel/cps-expansion-panel.component.cy.ts
  projects/cps-ui-kit/src/lib/components/cps-expansion-panel/cps-expansion-panel.component.html
  projects/cps-ui-kit/src/lib/components/cps-expansion-panel/cps-expansion-panel.component.scss
  projects/cps-ui-kit/src/lib/components/cps-expansion-panel/cps-expansion-panel.component.ts
  projects/cps-ui-kit/src/lib/components/cps-tab-group/cps-tab-group.component.html
  projects/cps-ui-kit/src/lib/components/cps-tab-group/cps-tab-group.component.scss
  projects/cps-ui-kit/src/lib/components/cps-tab-group/cps-tab-group.component.ts
Labels: bug, library

#336 Retrieve annotations for setter props
  api-generator/api-generator.js
  projects/composition/src/app/api-data/cps-autocomplete.json
  projects/composition/src/app/api-data/cps-button-toggle.json
  projects/composition/src/app/api-data/cps-checkbox.json
  projects/composition/src/app/api-data/cps-datepicker.json
  projects/composition/src/app/api-data/cps-input.json
  projects/composition/src/app/api-data/cps-radio-group.json
  projects/composition/src/app/api-data/cps-select.json
  projects/composition/src/app/api-data/cps-tab-group.json
  projects/composition/src/app/api-data/cps-table.json
  projects/composition/src/app/api-data/cps-tag.json
  projects/composition/src/app/api-data/cps-textarea.json
  projects/composition/src/app/api-data/cps-timepicker.json
  projects/composition/src/app/api-data/cps-tree-autocomplete.json
  projects/composition/src/app/api-data/cps-tree-select.json
  projects/composition/src/app/api-data/cps-tree-table.json
  projects/composition/src/app/api-data/internal.json
  projects/composition/src/app/components/component-docs-viewer/component-docs-viewer.component.html
  projects/composition/src/app/components/service-docs-viewer/service-docs-viewer.component.html
  projects/cps-ui-kit/src/lib/components/cps-autocomplete/cps-autocomplete.component.ts
  projects/cps-ui-kit/src/lib/components/cps-button-toggle/cps-button-toggle.component.ts
  projects/cps-ui-kit/src/lib/components/cps-radio-group/cps-radio-group.component.ts
  projects/cps-ui-kit/src/lib/components/cps-select/cps-select.component.ts
Labels: bug, composition

#344 Fix radio groups in scheduler component
  projects/cps-ui-kit/src/lib/components/cps-scheduler/cps-scheduler.component.html
Labels: bug, library

#345 Add left caret icon
  projects/cps-ui-kit/assets/icons.svg
  projects/cps-ui-kit/src/lib/components/cps-icon/cps-icon.component.ts
Labels: enhancement, library
