Repository AbsaOSS/cps-shared-ui, pull requests merged in 2025-01, with the labels that each got.

#413 Add measurement icon
  projects/cps-ui-kit/assets/icons.svg
  projects/cps-ui-kit/src/lib/components/cps-icon/cps-icon.component.ts
Labels: enhancement, library

#414 Update size & color of the measurement icon
  projects/cps-ui-kit/assets/icons.svg
Labels: bug, library

#418 #4 17 - Set up workflows for automatic repository release
  .github/workflows/check_pr_release_notes.yml
  .github/workflows/release_draft.yml
Labels: infrastructure
