Repository AbsaOSS/cps-shared-ui, pull requests merged in 2025-09, with the labels that each got.

#438 Sanitize tooltip content
  cypress/tsconfig.json
  projects/cps-ui-kit/src/lib/directives/cps-tooltip/cps-tooltip.directive.spec.ts
  projects/cps-ui-kit/src/lib/directives/cps-tooltip/cps-tooltip.directive.ts
  tsconfig.json
Labels: security

#439 Replace \r\n with \n in docs
  projects/composition/src/app/api-data/cps-notification.json
  projects/composition/src/app/api-data/cps-table.json
  projects/composition/src/app/api-data/cps-tree-table.json
Labels: skip-release-notes

#442 Fix/441 cron scheduler improve
  cypress/e2e/cps-scheduler.cy.ts
  projects/cps-ui-kit/src/lib/components/cps-autocomplete/cps-autocomplete.component.spec.ts
  projects/cps-ui-kit/src/lib/components/cps-scheduler/cps-scheduler.component.html
  projects/cps-ui-kit/src/lib/components/cps-scheduler/cps-scheduler.component.spec.ts
  projects/cps-ui-kit/src/lib/components/cps-scheduler/cps-scheduler.component.ts
  projects/cps-ui-kit/src/lib/services/cron-validation.service.spec.ts
  projects/cps-ui-kit/src/lib/services/cron-validation.service.ts
Labels: bug

#443 Add docs for CronValidationService
  projects/composition/src/app/api-data/cron-validation.service.json
  projects/cps-ui-kit/src/lib/services/cron-validation.service.ts
Labels: documentation, skip-release-notes
